import { AccountType } from "@prisma/client";

export type DefaultAccountTemplateRow = {
  code: string;
  name: string;
  type: AccountType;
  rootType: AccountType;
  isGroup: boolean;
  parentCode: string | null;
};

export const defaultChartOfAccountsTemplate: DefaultAccountTemplateRow[] = [
  { code: "1000", name: "Application of Funds (Assets)", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: true, parentCode: null },
  { code: "1100-1600", name: "Current Assets", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: true, parentCode: "1000" },
  { code: "1100", name: "Cash In Hand", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: true, parentCode: "1100-1600" },
  { code: "1110", name: "Cash", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1100" },
  { code: "1200", name: "Bank Accounts", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1100-1600" },
  { code: "1300", name: "Accounts Receivable", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: true, parentCode: "1100-1600" },
  { code: "1310", name: "Debtors", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1300" },
  { code: "1400", name: "Stock Assets", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: true, parentCode: "1100-1600" },
  { code: "1410", name: "Stock In Hand", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1400" },
  { code: "1500", name: "Tax Assets", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1100-1600" },
  { code: "1600", name: "Loans and Advances (Assets)", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: true, parentCode: "1100-1600" },
  { code: "1610", name: "Employee Advances", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1600" },
  { code: "1650", name: "Securities and Deposits", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: true, parentCode: "1600" },
  { code: "1651", name: "Earnest Money", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1650" },
  { code: "1660", name: "Prepaid Expenses", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1600" },
  { code: "1670", name: "Short-term Investments", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1600" },
  { code: "1700", name: "Fixed Assets", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: true, parentCode: "1000" },
  { code: "1710", name: "Capital Equipment", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1700" },
  { code: "1720", name: "Electronic Equipment", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1700" },
  { code: "1730", name: "Furniture and Fixtures", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1700" },
  { code: "1740", name: "Office Equipment", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1700" },
  { code: "1750", name: "Plants and Machineries", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1700" },
  { code: "1760", name: "Buildings", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1700" },
  { code: "1770", name: "Software", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1700" },
  { code: "1780", name: "Accumulated Depreciation", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1700" },
  { code: "1790", name: "CWIP Account", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1700" },
  { code: "1800", name: "Investments", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1000" },
  { code: "1900", name: "Temporary Accounts", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: true, parentCode: "1000" },
  { code: "1910", name: "Temporary Opening", type: AccountType.ASSET, rootType: AccountType.ASSET, isGroup: false, parentCode: "1900" },

  { code: "2000", name: "Source of Funds (Liabilities)", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: true, parentCode: null },
  { code: "2100-2400", name: "Current Liabilities", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: true, parentCode: "2000" },
  { code: "2100", name: "Accounts Payable", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: true, parentCode: "2100-2400" },
  { code: "2110", name: "Creditors", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2100" },
  { code: "2120", name: "Payroll Payable", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2100-2400" },
  { code: "2150", name: "Accrued Expenses", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2100-2400" },
  { code: "2160", name: "Customer Advances", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2100-2400" },
  { code: "2200", name: "Stock Liabilities", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: true, parentCode: "2100-2400" },
  { code: "2210", name: "Stock Received But Not Billed", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2200" },
  { code: "2211", name: "Asset Received But Not Billed", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2200" },
  { code: "2300", name: "Duties and Taxes", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: true, parentCode: "2100-2400" },
  { code: "2310", name: "TDS Payable", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2300" },
  { code: "2350", name: "Short-term Provisions", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2100-2400" },
  { code: "2400", name: "Loans (Liabilities)", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: true, parentCode: "2100-2400" },
  { code: "2410", name: "Secured Loans", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2400" },
  { code: "2420", name: "Unsecured Loans", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2400" },
  { code: "2430", name: "Bank Overdraft Account", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2400" },
  { code: "2500", name: "Non-Current Liabilities", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: true, parentCode: "2000" },
  { code: "2510", name: "Long-term Provisions", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2500" },
  { code: "2520", name: "Employee Benefits Obligation", type: AccountType.LIABILITY, rootType: AccountType.LIABILITY, isGroup: false, parentCode: "2500" },

  { code: "3000", name: "Equity", type: AccountType.EQUITY, rootType: AccountType.EQUITY, isGroup: true, parentCode: null },
  { code: "3100", name: "Capital Stock", type: AccountType.EQUITY, rootType: AccountType.EQUITY, isGroup: false, parentCode: "3000" },
  { code: "3200", name: "Dividends Paid", type: AccountType.EQUITY, rootType: AccountType.EQUITY, isGroup: false, parentCode: "3000" },
  { code: "3300", name: "Opening Balance Equity", type: AccountType.EQUITY, rootType: AccountType.EQUITY, isGroup: false, parentCode: "3000" },
  { code: "3400", name: "Retained Earnings", type: AccountType.EQUITY, rootType: AccountType.EQUITY, isGroup: false, parentCode: "3000" },
  { code: "3500", name: "Revaluation Surplus", type: AccountType.EQUITY, rootType: AccountType.EQUITY, isGroup: false, parentCode: "3000" },

  { code: "4000", name: "Income", type: AccountType.INCOME, rootType: AccountType.INCOME, isGroup: true, parentCode: null },
  { code: "4100", name: "Direct Income", type: AccountType.INCOME, rootType: AccountType.INCOME, isGroup: true, parentCode: "4000" },
  { code: "4110", name: "Sales", type: AccountType.INCOME, rootType: AccountType.INCOME, isGroup: false, parentCode: "4100" },
  { code: "4120", name: "Service", type: AccountType.INCOME, rootType: AccountType.INCOME, isGroup: false, parentCode: "4100" },
  { code: "4200", name: "Indirect Income", type: AccountType.INCOME, rootType: AccountType.INCOME, isGroup: true, parentCode: "4000" },
  { code: "4210", name: "Interest Income", type: AccountType.INCOME, rootType: AccountType.INCOME, isGroup: false, parentCode: "4200" },
  { code: "4220", name: "Interest on Fixed Deposits", type: AccountType.INCOME, rootType: AccountType.INCOME, isGroup: false, parentCode: "4200" },

  { code: "5000", name: "Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: true, parentCode: null },
  { code: "5100", name: "Direct Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: true, parentCode: "5000" },
  { code: "5110", name: "Stock Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: true, parentCode: "5100" },
  { code: "5111", name: "Cost of Goods Sold", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5110" },
  { code: "5112", name: "Expenses Included In Asset Valuation", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5110" },
  { code: "5118", name: "Expenses Included In Valuation", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5110" },
  { code: "5119", name: "Stock Adjustment", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5110" },
  { code: "5200", name: "Indirect Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: true, parentCode: "5000" },
  { code: "5201", name: "Administrative Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5202", name: "Commission on Sales", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5203", name: "Depreciation", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5204", name: "Entertainment Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5205", name: "Freight and Forwarding Charges", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5206", name: "Legal Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5207", name: "Marketing Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5208", name: "Office Maintenance Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5209", name: "Office Rent", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5210", name: "Postal Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5211", name: "Print and Stationery", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5212", name: "Round Off", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5213", name: "Salary", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5214", name: "Sales Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5215", name: "Telephone Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5216", name: "Travel Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5217", name: "Utility Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5218", name: "Write Off", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5219", name: "Exchange Gain/Loss", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5220", name: "Interest Expense", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5221", name: "Bank Charges", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5222", name: "Gain/Loss on Asset Disposal", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5223", name: "Miscellaneous Expenses", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5224", name: "Impairment", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
  { code: "5225", name: "Tax Expense", type: AccountType.EXPENSE, rootType: AccountType.EXPENSE, isGroup: false, parentCode: "5200" },
];

export const defaultChartOfAccountsCodes = new Set(defaultChartOfAccountsTemplate.map((row) => row.code));
