export const permissionCatalog = {
  "inventory.read": { module: "inventory", description: "Read inventory entities" },
  "inventory.write": { module: "inventory", description: "Create/update inventory entities" },
  "inventory.approve": { module: "inventory", description: "Approve inventory documents" },
  "inventory.item.read": { module: "inventory", description: "Read inventory items" },
  "inventory.item.write": { module: "inventory", description: "Create/update inventory items" },
  "inventory.item.delete": { module: "inventory", description: "Delete inventory items" },
  "inventory.document.read": { module: "inventory", description: "Read inventory documents" },
  "inventory.document.write": { module: "inventory", description: "Create/update inventory documents" },
  "inventory.document.approve": { module: "inventory", description: "Approve inventory documents" },
  "inventory.document.post": { module: "inventory", description: "Post inventory documents" },
  "inventory.ledger.read": { module: "inventory", description: "Read inventory ledger" },
  "inventory.settings.read": { module: "inventory", description: "Read inventory settings" },
  "inventory.settings.write": { module: "inventory", description: "Manage inventory settings" },
  "inventory.import.read": { module: "inventory", description: "Read inventory import jobs" },
  "inventory.import.write": { module: "inventory", description: "Create inventory imports" },
  "inventory.export.read": { module: "inventory", description: "Read inventory exports" },
  "inventory.export.write": { module: "inventory", description: "Create inventory exports" },
  "inventory.attachment.read": { module: "inventory", description: "Read inventory attachments" },
  "inventory.attachment.write": { module: "inventory", description: "Upload inventory attachments" },
  "inventory.overrideNegativeStock": { module: "inventory", description: "Override negative stock checks" },
  "sales.read": { module: "sales", description: "Read sales data" },
  "sales.write": { module: "sales", description: "Create/update sales data" },
  "finance.read": { module: "finance", description: "Read financial data" },
  "finance.write": { module: "finance", description: "Create/update financial data" },
  "admin.members": { module: "admin", description: "Manage tenant members" },
  "admin.roles": { module: "admin", description: "Manage tenant roles" },
  "admin.settings": { module: "admin", description: "Manage tenant settings/policies" },
  "iam.audit.read": { module: "iam", description: "Read IAM audit logs" },
  "iam.sessions.revoke": { module: "iam", description: "Revoke user sessions" },
  "iam.impersonate": { module: "iam", description: "Impersonate user sessions" },
} as const;

export type PermissionKey = keyof typeof permissionCatalog;

export const defaultRolePermissions: Record<string, PermissionKey[]> = {
  OWNER: Object.keys(permissionCatalog) as PermissionKey[],
  ADMIN: [
    "inventory.read",
    "inventory.write",
    "inventory.approve",
    "inventory.item.read",
    "inventory.item.write",
    "inventory.item.delete",
    "inventory.document.read",
    "inventory.document.write",
    "inventory.document.approve",
    "inventory.document.post",
    "inventory.ledger.read",
    "inventory.settings.read",
    "inventory.settings.write",
    "inventory.import.read",
    "inventory.import.write",
    "inventory.export.read",
    "inventory.export.write",
    "inventory.attachment.read",
    "inventory.attachment.write",
    "inventory.overrideNegativeStock",
    "sales.read",
    "sales.write",
    "finance.read",
    "finance.write",
    "admin.members",
    "admin.roles",
    "admin.settings",
    "iam.audit.read",
    "iam.sessions.revoke",
  ],
  MANAGER: [
    "inventory.read",
    "inventory.write",
    "inventory.item.read",
    "inventory.item.write",
    "inventory.document.read",
    "inventory.document.write",
    "inventory.document.approve",
    "inventory.document.post",
    "inventory.ledger.read",
    "inventory.settings.read",
    "inventory.settings.write",
    "sales.read",
    "sales.write",
    "finance.read",
  ],
  INVENTORY_MANAGER: [
    "inventory.read",
    "inventory.write",
    "inventory.approve",
    "inventory.item.read",
    "inventory.item.write",
    "inventory.item.delete",
    "inventory.document.read",
    "inventory.document.write",
    "inventory.document.approve",
    "inventory.document.post",
    "inventory.ledger.read",
    "inventory.settings.read",
    "inventory.settings.write",
    "inventory.import.read",
    "inventory.import.write",
    "inventory.export.read",
    "inventory.export.write",
    "inventory.attachment.read",
    "inventory.attachment.write",
    "inventory.overrideNegativeStock",
  ],
  SALES_MANAGER: [
    "sales.read",
    "sales.write",
    "inventory.read",
    "inventory.item.read",
    "inventory.document.read",
    "finance.read",
  ],
  FINANCE_MANAGER: [
    "finance.read",
    "finance.write",
    "sales.read",
    "inventory.read",
    "inventory.ledger.read",
    "inventory.export.read",
  ],
  PROCUREMENT_MANAGER: [
    "inventory.read",
    "inventory.write",
    "inventory.item.read",
    "inventory.item.write",
    "inventory.document.read",
    "inventory.document.write",
    "inventory.settings.read",
    "finance.read",
  ],
  MEMBER: ["inventory.read", "inventory.item.read", "inventory.document.read", "sales.read", "finance.read"],
  VIEWER: ["inventory.read", "inventory.item.read", "inventory.document.read", "inventory.ledger.read", "sales.read", "finance.read"],
  AUDITOR: ["inventory.read", "inventory.item.read", "inventory.document.read", "inventory.ledger.read", "inventory.export.read", "sales.read", "finance.read", "iam.audit.read"],
};

export const defaultRoleDescriptions: Record<string, string> = {
  OWNER: "Tenant owner with unrestricted access",
  ADMIN: "Tenant administrator",
  MANAGER: "Operational manager",
  INVENTORY_MANAGER: "Inventory operations manager",
  SALES_MANAGER: "Sales operations manager",
  FINANCE_MANAGER: "Finance manager",
  PROCUREMENT_MANAGER: "Procurement manager",
  MEMBER: "Regular member",
  VIEWER: "Read-only access",
  AUDITOR: "Read-only + audit visibility",
};
