export const permissionCatalog = {
  "inventory.read": { module: "inventory", description: "Read inventory entities" },
  "inventory.write": { module: "inventory", description: "Create/update inventory entities" },
  "inventory.approve": { module: "inventory", description: "Approve inventory documents" },
  "inventory.item.read": { module: "inventory", description: "Read inventory items" },
  "inventory.item.write": { module: "inventory", description: "Create/update inventory items" },
  "inventory.item.delete": { module: "inventory", description: "Delete inventory items" },
  "inventory.document.read": { module: "inventory", description: "Read inventory documents" },
  "inventory.document.write": { module: "inventory", description: "Create/update inventory documents" },
  "inventory.document.approve": { module: "inventory", description: "Approve inventory documents" },
  "inventory.document.post": { module: "inventory", description: "Post inventory documents" },
  "inventory.ledger.read": { module: "inventory", description: "Read inventory ledger" },
  "inventory.settings.read": { module: "inventory", description: "Read inventory settings" },
  "inventory.settings.write": { module: "inventory", description: "Manage inventory settings" },
  "inventory.admin.ops": { module: "inventory", description: "Run inventory admin operations" },
  "inventory.import.read": { module: "inventory", description: "Read inventory import jobs" },
  "inventory.import.write": { module: "inventory", description: "Create inventory imports" },
  "inventory.export.read": { module: "inventory", description: "Read inventory exports" },
  "inventory.export.write": { module: "inventory", description: "Create inventory exports" },
  "inventory.attachment.read": { module: "inventory", description: "Read inventory attachments" },
  "inventory.attachment.write": { module: "inventory", description: "Upload inventory attachments" },
  "inventory.overrideNegativeStock": { module: "inventory", description: "Override negative stock checks" },
  "sales.read": { module: "sales", description: "Read sales data" },
  "sales.write": { module: "sales", description: "Create/update sales data" },
  "finance.read": { module: "finance", description: "Read financial data" },
  "finance.write": { module: "finance", description: "Create/update financial data" },
  "accounting.account.read": { module: "accounting", description: "Read chart of accounts" },
  "accounting.account.write": { module: "accounting", description: "Manage chart of accounts" },
  "accounting.journal.read": { module: "accounting", description: "Read journal entries" },
  "accounting.journal.write": { module: "accounting", description: "Create/update draft journal entries" },
  "accounting.journal.submit": { module: "accounting", description: "Submit and post journal entries" },
  "accounting.gl.read": { module: "accounting", description: "Read general ledger entries" },
  "accounting.period.read": { module: "accounting", description: "Read fiscal years and periods" },
  "accounting.period.write": { module: "accounting", description: "Manage fiscal years and periods" },
  "accounting.report.read": { module: "accounting", description: "Read accounting reports" },
  "admin.members": { module: "admin", description: "Manage tenant members" },
  "admin.roles": { module: "admin", description: "Manage tenant roles" },
  "admin.settings": { module: "admin", description: "Manage tenant settings/policies" },
  "iam.audit.read": { module: "iam", description: "Read IAM audit logs" },
  "iam.sessions.revoke": { module: "iam", description: "Revoke user sessions" },
  "iam.impersonate": { module: "iam", description: "Impersonate user sessions" },
  "platform.tenants.read": { module: "platform", description: "Read tenant and company hierarchy" },
  "platform.tenants.write": { module: "platform", description: "Create/update tenant and company hierarchy" },
  "platform.rbac.read": { module: "platform", description: "Read role profiles and scope rules" },
  "platform.rbac.write": { module: "platform", description: "Manage role profiles and scope rules" },
  "platform.workflow.read": { module: "platform", description: "Read workflow definitions and instances" },
  "platform.workflow.write": { module: "platform", description: "Manage workflow definitions and transitions" },
  "platform.audit.read": { module: "platform", description: "Read platform audit events" },
  "platform.ledger.read": { module: "platform", description: "Read immutable ledger verification and events" },
  "platform.numbering.read": { module: "platform", description: "Read numbering series definitions" },
  "platform.numbering.write": { module: "platform", description: "Manage numbering series and allocate numbers" },
  "platform.reporting.read": { module: "platform", description: "Read and run platform reports" },
  "platform.reporting.write": { module: "platform", description: "Manage report definitions, views, and schedules" },
  "platform.customization.read": { module: "platform", description: "Read metadata customization definitions" },
  "platform.customization.write": { module: "platform", description: "Manage metadata customization definitions" },
} as const;

export type PermissionKey = keyof typeof permissionCatalog;

export const defaultRolePermissions: Record<string, PermissionKey[]> = {
  OWNER: Object.keys(permissionCatalog) as PermissionKey[],
  ADMIN: [
    "inventory.read",
    "inventory.write",
    "inventory.approve",
    "inventory.item.read",
    "inventory.item.write",
    "inventory.item.delete",
    "inventory.document.read",
    "inventory.document.write",
    "inventory.document.approve",
    "inventory.document.post",
    "inventory.ledger.read",
    "inventory.settings.read",
    "inventory.settings.write",
    "inventory.admin.ops",
    "inventory.import.read",
    "inventory.import.write",
    "inventory.export.read",
    "inventory.export.write",
    "inventory.attachment.read",
    "inventory.attachment.write",
    "inventory.overrideNegativeStock",
    "sales.read",
    "sales.write",
    "finance.read",
    "finance.write",
    "accounting.account.read",
    "accounting.account.write",
    "accounting.journal.read",
    "accounting.journal.write",
    "accounting.journal.submit",
    "accounting.gl.read",
    "accounting.period.read",
    "accounting.period.write",
    "accounting.report.read",
    "admin.members",
    "admin.roles",
    "admin.settings",
    "iam.audit.read",
    "iam.sessions.revoke",
    "platform.tenants.read",
    "platform.tenants.write",
    "platform.rbac.read",
    "platform.rbac.write",
    "platform.workflow.read",
    "platform.workflow.write",
    "platform.audit.read",
    "platform.ledger.read",
    "platform.numbering.read",
    "platform.numbering.write",
    "platform.reporting.read",
    "platform.reporting.write",
    "platform.customization.read",
    "platform.customization.write",
  ],
  MANAGER: [
    "inventory.read",
    "inventory.write",
    "inventory.item.read",
    "inventory.item.write",
    "inventory.document.read",
    "inventory.document.write",
    "inventory.document.approve",
    "inventory.document.post",
    "inventory.ledger.read",
    "inventory.settings.read",
    "inventory.settings.write",
    "inventory.admin.ops",
    "sales.read",
    "sales.write",
    "finance.read",
    "accounting.account.read",
    "accounting.journal.read",
    "accounting.gl.read",
    "accounting.period.read",
    "accounting.report.read",
    "platform.workflow.read",
    "platform.reporting.read",
    "platform.customization.read",
  ],
  INVENTORY_MANAGER: [
    "inventory.read",
    "inventory.write",
    "inventory.approve",
    "inventory.item.read",
    "inventory.item.write",
    "inventory.item.delete",
    "inventory.document.read",
    "inventory.document.write",
    "inventory.document.approve",
    "inventory.document.post",
    "inventory.ledger.read",
    "inventory.settings.read",
    "inventory.settings.write",
    "inventory.admin.ops",
    "inventory.import.read",
    "inventory.import.write",
    "inventory.export.read",
    "inventory.export.write",
    "inventory.attachment.read",
    "inventory.attachment.write",
    "inventory.overrideNegativeStock",
  ],
  SALES_MANAGER: [
    "sales.read",
    "sales.write",
    "inventory.read",
    "inventory.item.read",
    "inventory.document.read",
    "finance.read",
  ],
  FINANCE_MANAGER: [
    "finance.read",
    "finance.write",
    "accounting.account.read",
    "accounting.account.write",
    "accounting.journal.read",
    "accounting.journal.write",
    "accounting.journal.submit",
    "accounting.gl.read",
    "accounting.period.read",
    "accounting.period.write",
    "accounting.report.read",
    "sales.read",
    "inventory.read",
    "inventory.ledger.read",
    "inventory.export.read",
  ],
  PROCUREMENT_MANAGER: [
    "inventory.read",
    "inventory.write",
    "inventory.item.read",
    "inventory.item.write",
    "inventory.document.read",
    "inventory.document.write",
    "inventory.settings.read",
    "finance.read",
    "platform.reporting.read",
  ],
  MEMBER: [
    "inventory.read",
    "inventory.item.read",
    "inventory.document.read",
    "sales.read",
    "finance.read",
    "accounting.account.read",
    "accounting.journal.read",
    "accounting.gl.read",
    "accounting.period.read",
    "accounting.report.read",
    "platform.reporting.read",
  ],
  VIEWER: [
    "inventory.read",
    "inventory.item.read",
    "inventory.document.read",
    "inventory.ledger.read",
    "sales.read",
    "finance.read",
    "accounting.account.read",
    "accounting.journal.read",
    "accounting.gl.read",
    "accounting.period.read",
    "accounting.report.read",
    "platform.reporting.read",
  ],
  AUDITOR: [
    "inventory.read",
    "inventory.item.read",
    "inventory.document.read",
    "inventory.ledger.read",
    "inventory.export.read",
    "sales.read",
    "finance.read",
    "iam.audit.read",
    "platform.audit.read",
    "platform.ledger.read",
    "platform.reporting.read",
  ],
};

export const defaultRoleDescriptions: Record<string, string> = {
  OWNER: "Tenant owner with unrestricted access",
  ADMIN: "Tenant administrator",
  MANAGER: "Operational manager",
  INVENTORY_MANAGER: "Inventory operations manager",
  SALES_MANAGER: "Sales operations manager",
  FINANCE_MANAGER: "Finance manager",
  PROCUREMENT_MANAGER: "Procurement manager",
  MEMBER: "Regular member",
  VIEWER: "Read-only access",
  AUDITOR: "Read-only + audit visibility",
};
